namespace THOK.Wms.Repository.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class zxladdTable : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.wms_move_bill_master", "bill_type_code", "dbo.wms_bill_type");
            DropForeignKey("dbo.wms_move_bill_master", "warehouse_code", "dbo.wms_warehouse");
            DropForeignKey("dbo.wms_move_bill_master", "Employee_ID", "dbo.wms_employee");
            DropForeignKey("dbo.wms_check_bill_master", "bill_type_code", "dbo.wms_bill_type");
            DropForeignKey("dbo.wms_check_bill_master", "warehouse_code", "dbo.wms_warehouse");
            DropForeignKey("dbo.wms_check_bill_master", "Employee_ID", "dbo.wms_employee");
            DropForeignKey("dbo.wms_daily_balance", "warehouse_code", "dbo.wms_warehouse");
            DropForeignKey("dbo.wms_daily_balance", "product_code", "dbo.wms_product");
            DropForeignKey("dbo.wms_daily_balance", "unit_code", "dbo.wms_unit");
            DropForeignKey("dbo.wms_move_bill_detail", "product_code", "dbo.wms_product");
            DropForeignKey("dbo.wms_move_bill_detail", "unit_code", "dbo.wms_unit");
            DropForeignKey("dbo.wms_move_bill_detail", "Storage_StorageCode", "dbo.wms_storage");
            DropForeignKey("dbo.wms_move_bill_detail", "Cell_CellCode", "dbo.wms_cell");
            DropForeignKey("dbo.wms_check_bill_detail", "cell_code", "dbo.wms_cell");
            DropForeignKey("dbo.wms_check_bill_detail", "storage_code", "dbo.wms_storage");
            DropForeignKey("dbo.wms_check_bill_detail", "Unit_UnitCode1", "dbo.wms_unit");
            DropForeignKey("dbo.wms_check_bill_detail", "Product_ProductCode1", "dbo.wms_product");
            DropIndex("dbo.wms_move_bill_master", new[] { "bill_type_code" });
            DropIndex("dbo.wms_move_bill_master", new[] { "warehouse_code" });
            DropIndex("dbo.wms_move_bill_master", new[] { "Employee_ID" });
            DropIndex("dbo.wms_check_bill_master", new[] { "bill_type_code" });
            DropIndex("dbo.wms_check_bill_master", new[] { "warehouse_code" });
            DropIndex("dbo.wms_check_bill_master", new[] { "Employee_ID" });
            DropIndex("dbo.wms_daily_balance", new[] { "warehouse_code" });
            DropIndex("dbo.wms_daily_balance", new[] { "product_code" });
            DropIndex("dbo.wms_daily_balance", new[] { "unit_code" });
            DropIndex("dbo.wms_move_bill_detail", new[] { "product_code" });
            DropIndex("dbo.wms_move_bill_detail", new[] { "unit_code" });
            DropIndex("dbo.wms_move_bill_detail", new[] { "Storage_StorageCode" });
            DropIndex("dbo.wms_move_bill_detail", new[] { "Cell_CellCode" });
            DropIndex("dbo.wms_check_bill_detail", new[] { "cell_code" });
            DropIndex("dbo.wms_check_bill_detail", new[] { "storage_code" });
            DropIndex("dbo.wms_check_bill_detail", new[] { "Unit_UnitCode1" });
            DropIndex("dbo.wms_check_bill_detail", new[] { "Product_ProductCode1" });
            RenameColumn(table: "dbo.wms_move_bill_master", name: "OperatePerson_ID", newName: "operate_person_id");
            RenameColumn(table: "dbo.wms_move_bill_master", name: "VerifyPerson_ID", newName: "verify_person_id");
            RenameColumn(table: "dbo.wms_check_bill_master", name: "OperatePerson_ID", newName: "operate_person_id");
            RenameColumn(table: "dbo.wms_check_bill_master", name: "VerifyPerson_ID", newName: "verify_person_id");
            RenameColumn(table: "dbo.wms_move_bill_detail", name: "OperatePerson_ID", newName: "operate_person_id");
            RenameColumn(table: "dbo.wms_move_bill_detail", name: "OutCell_CellCode", newName: "out_cell_code");
            RenameColumn(table: "dbo.wms_move_bill_detail", name: "InCell_CellCode", newName: "in_cell_code");
            RenameColumn(table: "dbo.wms_move_bill_detail", name: "OutStorage_StorageCode", newName: "out_storage_code");
            RenameColumn(table: "dbo.wms_move_bill_detail", name: "InStorage_StorageCode", newName: "in_storage_code");
            RenameColumn(table: "dbo.wms_check_bill_detail", name: "Product_ProductCode", newName: "product_code");
            RenameColumn(table: "dbo.wms_check_bill_detail", name: "Unit_UnitCode", newName: "unit_code");
            RenameColumn(table: "dbo.wms_check_bill_detail", name: "RealProduct_ProductCode", newName: "real_product_code");
            RenameColumn(table: "dbo.wms_check_bill_detail", name: "RealUnit_UnitCode", newName: "real_unit_code");
            RenameColumn(table: "dbo.wms_check_bill_detail", name: "OperatePerson_ID", newName: "operate_person_id");
            AddForeignKey("dbo.wms_move_bill_master", "bill_type_code", "dbo.wms_bill_type", "bill_type_code");
            AddForeignKey("dbo.wms_move_bill_master", "warehouse_code", "dbo.wms_warehouse", "warehouse_code");
            AddForeignKey("dbo.wms_check_bill_master", "bill_type_code", "dbo.wms_bill_type", "bill_type_code");
            AddForeignKey("dbo.wms_check_bill_master", "warehouse_code", "dbo.wms_warehouse", "warehouse_code");
            AddForeignKey("dbo.wms_daily_balance", "warehouse_code", "dbo.wms_warehouse", "warehouse_code");
            AddForeignKey("dbo.wms_daily_balance", "product_code", "dbo.wms_product", "product_code");
            AddForeignKey("dbo.wms_daily_balance", "unit_code", "dbo.wms_unit", "unit_code");
            AddForeignKey("dbo.wms_move_bill_detail", "product_code", "dbo.wms_product", "product_code");
            AddForeignKey("dbo.wms_move_bill_detail", "unit_code", "dbo.wms_unit", "unit_code");
            AddForeignKey("dbo.wms_check_bill_detail", "cell_code", "dbo.wms_cell", "cell_code");
            AddForeignKey("dbo.wms_check_bill_detail", "storage_code", "dbo.wms_storage", "storage_code");
            CreateIndex("dbo.wms_move_bill_master", "bill_type_code");
            CreateIndex("dbo.wms_move_bill_master", "warehouse_code");
            CreateIndex("dbo.wms_check_bill_master", "bill_type_code");
            CreateIndex("dbo.wms_check_bill_master", "warehouse_code");
            CreateIndex("dbo.wms_daily_balance", "warehouse_code");
            CreateIndex("dbo.wms_daily_balance", "product_code");
            CreateIndex("dbo.wms_daily_balance", "unit_code");
            CreateIndex("dbo.wms_move_bill_detail", "product_code");
            CreateIndex("dbo.wms_move_bill_detail", "unit_code");
            CreateIndex("dbo.wms_check_bill_detail", "cell_code");
            CreateIndex("dbo.wms_check_bill_detail", "storage_code");
            DropColumn("dbo.wms_move_bill_master", "operate_person_code");
            DropColumn("dbo.wms_move_bill_master", "verify_person_code");
            DropColumn("dbo.wms_move_bill_master", "Employee_ID");
            DropColumn("dbo.wms_check_bill_master", "operate_person_code");
            DropColumn("dbo.wms_check_bill_master", "verify_person_code");
            DropColumn("dbo.wms_check_bill_master", "Employee_ID");
            DropColumn("dbo.wms_move_bill_detail", "operate_person_code");
            DropColumn("dbo.wms_move_bill_detail", "Storage_StorageCode");
            DropColumn("dbo.wms_move_bill_detail", "Cell_CellCode");
            DropColumn("dbo.wms_check_bill_detail", "operate_person_code");
            DropColumn("dbo.wms_check_bill_detail", "Unit_UnitCode1");
            DropColumn("dbo.wms_check_bill_detail", "Product_ProductCode1");
        }
        
        public override void Down()
        {
            AddColumn("dbo.wms_check_bill_detail", "Product_ProductCode1", c => c.String(maxLength: 20));
            AddColumn("dbo.wms_check_bill_detail", "Unit_UnitCode1", c => c.String(maxLength: 20));
            AddColumn("dbo.wms_check_bill_detail", "operate_person_code", c => c.String(maxLength: 100));
            AddColumn("dbo.wms_move_bill_detail", "Cell_CellCode", c => c.String(maxLength: 20));
            AddColumn("dbo.wms_move_bill_detail", "Storage_StorageCode", c => c.String(maxLength: 50));
            AddColumn("dbo.wms_move_bill_detail", "operate_person_code", c => c.String(maxLength: 20));
            AddColumn("dbo.wms_check_bill_master", "Employee_ID", c => c.Guid());
            AddColumn("dbo.wms_check_bill_master", "verify_person_code", c => c.String(maxLength: 20));
            AddColumn("dbo.wms_check_bill_master", "operate_person_code", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.wms_move_bill_master", "Employee_ID", c => c.Guid());
            AddColumn("dbo.wms_move_bill_master", "verify_person_code", c => c.String(maxLength: 20));
            AddColumn("dbo.wms_move_bill_master", "operate_person_code", c => c.String(nullable: false, maxLength: 20));
            DropIndex("dbo.wms_check_bill_detail", new[] { "storage_code" });
            DropIndex("dbo.wms_check_bill_detail", new[] { "cell_code" });
            DropIndex("dbo.wms_move_bill_detail", new[] { "unit_code" });
            DropIndex("dbo.wms_move_bill_detail", new[] { "product_code" });
            DropIndex("dbo.wms_daily_balance", new[] { "unit_code" });
            DropIndex("dbo.wms_daily_balance", new[] { "product_code" });
            DropIndex("dbo.wms_daily_balance", new[] { "warehouse_code" });
            DropIndex("dbo.wms_check_bill_master", new[] { "warehouse_code" });
            DropIndex("dbo.wms_check_bill_master", new[] { "bill_type_code" });
            DropIndex("dbo.wms_move_bill_master", new[] { "warehouse_code" });
            DropIndex("dbo.wms_move_bill_master", new[] { "bill_type_code" });
            DropForeignKey("dbo.wms_check_bill_detail", "storage_code", "dbo.wms_storage");
            DropForeignKey("dbo.wms_check_bill_detail", "cell_code", "dbo.wms_cell");
            DropForeignKey("dbo.wms_move_bill_detail", "unit_code", "dbo.wms_unit");
            DropForeignKey("dbo.wms_move_bill_detail", "product_code", "dbo.wms_product");
            DropForeignKey("dbo.wms_daily_balance", "unit_code", "dbo.wms_unit");
            DropForeignKey("dbo.wms_daily_balance", "product_code", "dbo.wms_product");
            DropForeignKey("dbo.wms_daily_balance", "warehouse_code", "dbo.wms_warehouse");
            DropForeignKey("dbo.wms_check_bill_master", "warehouse_code", "dbo.wms_warehouse");
            DropForeignKey("dbo.wms_check_bill_master", "bill_type_code", "dbo.wms_bill_type");
            DropForeignKey("dbo.wms_move_bill_master", "warehouse_code", "dbo.wms_warehouse");
            DropForeignKey("dbo.wms_move_bill_master", "bill_type_code", "dbo.wms_bill_type");
            RenameColumn(table: "dbo.wms_check_bill_detail", name: "operate_person_id", newName: "OperatePerson_ID");
            RenameColumn(table: "dbo.wms_check_bill_detail", name: "real_unit_code", newName: "RealUnit_UnitCode");
            RenameColumn(table: "dbo.wms_check_bill_detail", name: "real_product_code", newName: "RealProduct_ProductCode");
            RenameColumn(table: "dbo.wms_check_bill_detail", name: "unit_code", newName: "Unit_UnitCode");
            RenameColumn(table: "dbo.wms_check_bill_detail", name: "product_code", newName: "Product_ProductCode");
            RenameColumn(table: "dbo.wms_move_bill_detail", name: "in_storage_code", newName: "InStorage_StorageCode");
            RenameColumn(table: "dbo.wms_move_bill_detail", name: "out_storage_code", newName: "OutStorage_StorageCode");
            RenameColumn(table: "dbo.wms_move_bill_detail", name: "in_cell_code", newName: "InCell_CellCode");
            RenameColumn(table: "dbo.wms_move_bill_detail", name: "out_cell_code", newName: "OutCell_CellCode");
            RenameColumn(table: "dbo.wms_move_bill_detail", name: "operate_person_id", newName: "OperatePerson_ID");
            RenameColumn(table: "dbo.wms_check_bill_master", name: "verify_person_id", newName: "VerifyPerson_ID");
            RenameColumn(table: "dbo.wms_check_bill_master", name: "operate_person_id", newName: "OperatePerson_ID");
            RenameColumn(table: "dbo.wms_move_bill_master", name: "verify_person_id", newName: "VerifyPerson_ID");
            RenameColumn(table: "dbo.wms_move_bill_master", name: "operate_person_id", newName: "OperatePerson_ID");
            CreateIndex("dbo.wms_check_bill_detail", "Product_ProductCode1");
            CreateIndex("dbo.wms_check_bill_detail", "Unit_UnitCode1");
            CreateIndex("dbo.wms_check_bill_detail", "storage_code");
            CreateIndex("dbo.wms_check_bill_detail", "cell_code");
            CreateIndex("dbo.wms_move_bill_detail", "Cell_CellCode");
            CreateIndex("dbo.wms_move_bill_detail", "Storage_StorageCode");
            CreateIndex("dbo.wms_move_bill_detail", "unit_code");
            CreateIndex("dbo.wms_move_bill_detail", "product_code");
            CreateIndex("dbo.wms_daily_balance", "unit_code");
            CreateIndex("dbo.wms_daily_balance", "product_code");
            CreateIndex("dbo.wms_daily_balance", "warehouse_code");
            CreateIndex("dbo.wms_check_bill_master", "Employee_ID");
            CreateIndex("dbo.wms_check_bill_master", "warehouse_code");
            CreateIndex("dbo.wms_check_bill_master", "bill_type_code");
            CreateIndex("dbo.wms_move_bill_master", "Employee_ID");
            CreateIndex("dbo.wms_move_bill_master", "warehouse_code");
            CreateIndex("dbo.wms_move_bill_master", "bill_type_code");
            AddForeignKey("dbo.wms_check_bill_detail", "Product_ProductCode1", "dbo.wms_product", "product_code");
            AddForeignKey("dbo.wms_check_bill_detail", "Unit_UnitCode1", "dbo.wms_unit", "unit_code");
            AddForeignKey("dbo.wms_check_bill_detail", "storage_code", "dbo.wms_storage", "storage_code", cascadeDelete: true);
            AddForeignKey("dbo.wms_check_bill_detail", "cell_code", "dbo.wms_cell", "cell_code", cascadeDelete: true);
            AddForeignKey("dbo.wms_move_bill_detail", "Cell_CellCode", "dbo.wms_cell", "cell_code");
            AddForeignKey("dbo.wms_move_bill_detail", "Storage_StorageCode", "dbo.wms_storage", "storage_code");
            AddForeignKey("dbo.wms_move_bill_detail", "unit_code", "dbo.wms_unit", "unit_code", cascadeDelete: true);
            AddForeignKey("dbo.wms_move_bill_detail", "product_code", "dbo.wms_product", "product_code", cascadeDelete: true);
            AddForeignKey("dbo.wms_daily_balance", "unit_code", "dbo.wms_unit", "unit_code", cascadeDelete: true);
            AddForeignKey("dbo.wms_daily_balance", "product_code", "dbo.wms_product", "product_code", cascadeDelete: true);
            AddForeignKey("dbo.wms_daily_balance", "warehouse_code", "dbo.wms_warehouse", "warehouse_code", cascadeDelete: true);
            AddForeignKey("dbo.wms_check_bill_master", "Employee_ID", "dbo.wms_employee", "employee_id");
            AddForeignKey("dbo.wms_check_bill_master", "warehouse_code", "dbo.wms_warehouse", "warehouse_code", cascadeDelete: true);
            AddForeignKey("dbo.wms_check_bill_master", "bill_type_code", "dbo.wms_bill_type", "bill_type_code", cascadeDelete: true);
            AddForeignKey("dbo.wms_move_bill_master", "Employee_ID", "dbo.wms_employee", "employee_id");
            AddForeignKey("dbo.wms_move_bill_master", "warehouse_code", "dbo.wms_warehouse", "warehouse_code", cascadeDelete: true);
            AddForeignKey("dbo.wms_move_bill_master", "bill_type_code", "dbo.wms_bill_type", "bill_type_code", cascadeDelete: true);
        }
    }
}
